# Generated by Django 5.0.3 on 2024-03-22 22:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrecadador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_created=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Arrecadador',
                'verbose_name_plural': 'Arrecadadores',
            },
        ),
        migrations.CreateModel(
            name='Vestuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_created=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('roupa', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Vestuario',
                'verbose_name_plural': 'vestuarios',
            },
        ),
        migrations.CreateModel(
            name='Arrecadacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_created=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tamanho', models.CharField(max_length=4)),
                ('genero', models.CharField(max_length=1)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('arrecadador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrecadacoes', to='CA.arrecadador')),
                ('vestuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrecadacoes', to='CA.vestuario')),
            ],
            options={
                'verbose_name': 'Arrecadacao',
                'verbose_name_plural': 'Arrecadacoes',
            },
        ),
    ]
