# Generated by Django 5.0.3 on 2024-03-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrecadacao',
            options={'verbose_name': 'Arrecadação', 'verbose_name_plural': 'Arrecadações'},
        ),
        migrations.AddField(
            model_name='arrecadador',
            name='cep',
            field=models.CharField(default='00000-000', max_length=8),
        ),
    ]
