# Generated by Django 5.0.3 on 2024-03-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0002_alter_arrecadacao_options_arrecadador_cep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_created=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('size', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
            },
        ),
    ]
