# Generated by Django 5.0.3 on 2024-04-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0004_alter_tamanho_options_alter_arrecadacao_tamanho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tamanho',
            options={'verbose_name': 'Tamanho', 'verbose_name_plural': 'Tamanhos'},
        ),
    ]
