# Generated by Django 5.0.3 on 2024-04-04 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0005_alter_tamanho_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrecadacao',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tamanhos', to='CA.tamanho'),
        ),
    ]
