# Generated by Django 5.0.3 on 2024-04-06 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0006_alter_arrecadacao_tamanho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tamanho',
            options={'verbose_name': 'tamanho', 'verbose_name_plural': 'tamanhos'},
        ),
        migrations.AlterField(
            model_name='arrecadacao',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='CA.tamanho'),
        ),
    ]
