# Generated by Django 5.0.6 on 2024-05-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0008_genero_alter_arrecadacao_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
